"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 01:14:41.571435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUM_TYPES = (
    'user_role',
    'user_status',
    'allocation_status',
    'internal_submission_status',
    'semester_result_status',
    'flag_rule',
    'flag_status',
    'slot_status',
    'meeting_status',
    'group_session_audience',
    'group_session_status',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('internal_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semesters')),
    sa.UniqueConstraint('name', name=op.f('uq_semesters_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'mentor', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'deactivated', name='user_status'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('roll_no', sa.String(length=30), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(length=10), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('roll_no', name=op.f('uq_users_roll_no'))
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='allocation_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_allocations_assigned_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_allocations_mentor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_allocations_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocations'))
    )
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocations_mentor_id'), ['mentor_id'], unique=False)
        batch_op.create_index('uq_one_active_allocation', ['student_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_entity_entity_id', ['entity', 'entity_id'], unique=False)

    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Enum('F1', 'F2', 'F3', 'F4', 'F5', name='flag_rule'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_discussion', 'resolved', 'escalated', name='flag_status'), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_flags_resolved_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_flags_semester_id_semesters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_flags_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flags'))
    )
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.create_index('uq_one_unresolved_flag', ['student_id', 'semester_id', 'rule'], unique=True, sqlite_where=sa.text("status IN ('open', 'in_discussion', 'escalated')"), postgresql_where=sa.text("status IN ('open', 'in_discussion', 'escalated')"))

    op.create_table('group_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('audience', sa.Enum('all', 'flagged', 'selected', name='group_session_audience'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='group_session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_group_sessions_mentor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_sessions'))
    )
    op.create_table('internal_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='internal_submission_status'), nullable=False),
    sa.Column('proof_url', sa.String(length=500), nullable=False),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_internal_submissions_semester_id_semesters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_internal_submissions_student_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_internal_submissions_verified_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_submissions'))
    )
    with op.batch_alter_table('internal_submissions', schema=None) as batch_op:
        batch_op.create_index('uq_one_live_internal_submission', ['student_id', 'semester_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'verified')"), postgresql_where=sa.text("status IN ('pending', 'verified')"))

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('semester_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('sgpa', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='semester_result_status'), nullable=False),
    sa.Column('proof_url', sa.String(length=500), nullable=False),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_semester_results_semester_id_semesters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_semester_results_student_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_semester_results_verified_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester_results'))
    )
    with op.batch_alter_table('semester_results', schema=None) as batch_op:
        batch_op.create_index('uq_one_live_semester_result', ['student_id', 'semester_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'verified')"), postgresql_where=sa.text("status IN ('pending', 'verified')"))

    op.create_table('slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'booked', 'completed', 'cancelled', name='slot_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_slots_mentor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots'))
    )
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slots_mentor_id'), ['mentor_id'], unique=False)

    op.create_table('group_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['group_sessions.id'], name=op.f('fk_group_attendance_session_id_group_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_group_attendance_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_attendance')),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_group_attendance_session_student')
    )
    op.create_table('internal_marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('i1', sa.Integer(), nullable=True),
    sa.Column('i2', sa.Integer(), nullable=True),
    sa.Column('i3', sa.Integer(), nullable=True),
    sa.Column('effective_internal', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['internal_submissions.id'], name=op.f('fk_internal_marks_submission_id_internal_submissions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_marks')),
    sa.UniqueConstraint('submission_id', 'subject_name', name='uq_internal_marks_submission_subject')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('invited_by_mentor', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_meetings_slot_id_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_meetings_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('uq_one_live_meeting_per_slot', ['slot_id'], unique=True, sqlite_where=sa.text("status IN ('scheduled', 'completed')"), postgresql_where=sa.text("status IN ('scheduled', 'completed')"))

    op.create_table('result_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['semester_results.id'], name=op.f('fk_result_subjects_result_id_semester_results'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_subjects')),
    sa.UniqueConstraint('result_id', 'subject_name', name='uq_result_subjects_result_subject')
    )
    op.create_table('meeting_flags',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], name=op.f('fk_meeting_flags_flag_id_flags'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_flags_meeting_id_meetings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('meeting_id', 'flag_id', name=op.f('pk_meeting_flags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_flags')
    op.drop_table('result_subjects')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('uq_one_live_meeting_per_slot', sqlite_where=sa.text("status IN ('scheduled', 'completed')"), postgresql_where=sa.text("status IN ('scheduled', 'completed')"))

    op.drop_table('meetings')
    op.drop_table('internal_marks')
    op.drop_table('group_attendance')
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_mentor_id'))

    op.drop_table('slots')
    with op.batch_alter_table('semester_results', schema=None) as batch_op:
        batch_op.drop_index('uq_one_live_semester_result', sqlite_where=sa.text("status IN ('pending', 'verified')"), postgresql_where=sa.text("status IN ('pending', 'verified')"))

    op.drop_table('semester_results')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('internal_submissions', schema=None) as batch_op:
        batch_op.drop_index('uq_one_live_internal_submission', sqlite_where=sa.text("status IN ('pending', 'verified')"), postgresql_where=sa.text("status IN ('pending', 'verified')"))

    op.drop_table('internal_submissions')
    op.drop_table('group_sessions')
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.drop_index('uq_one_unresolved_flag', sqlite_where=sa.text("status IN ('open', 'in_discussion', 'escalated')"), postgresql_where=sa.text("status IN ('open', 'in_discussion', 'escalated')"))

    op.drop_table('flags')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity_entity_id')

    op.drop_table('audit_log')
    with op.batch_alter_table('allocations', schema=None) as batch_op:
        batch_op.drop_index('uq_one_active_allocation', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_allocations_mentor_id'))

    op.drop_table('allocations')
    op.drop_table('users')
    op.drop_table('semesters')
    # ### end Alembic commands ###

    # PostgreSQL keeps enum types after their tables are dropped.
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name in ENUM_TYPES:
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
